In [50]:
import numpy as np
import scipy
import matplotlib.pyplot as plt
from astropy.io import fits
from scipy import optimize
import plotly.graph_objects as go
import plotly.express as px

In [45]:
import photutils
from photutils import centroid_com, centroid_2dg

In [4]:
def selectdata(array,position):
    Data = []
    for s in range(0,len(array)):
        Data.append(array[s][position])
    return Data

In [5]:
def ChooseMoreMoons(DayObv):
    if len(DayObv)!=0:
        Counts = []
        for h in range(0,len(DayObv)):
            s = 0
            if isinstance(DayObv[h],int): 
                s = 10
            else:
                for h1 in range(0,len(DayObv[h])):
                    if isinstance(DayObv[h][h1],int): s+=1
            Counts.append(s)
        for i in range(0,len(Counts)):
            if Counts[i] == min(Counts): return i

In [6]:
def distance(r1,r2,width):
    return (r2-r1)/width

In [7]:
class moon:
    def __init__(self,name,centroid,black,red,green,blue):
        self.centroid = centroid
        self.name = name
        self.rgb = [(red/np.sqrt(red*red + green*green + blue*blue)),(green/np.sqrt(red*red + green*green + blue*blue)),(blue/np.sqrt(red*red + green*green + blue*blue))]
        
class planet:
    def __init__(self,name,centroid,width):
        self.centroid = centroid
        self.name = name
        self.width = width

In [8]:
class OrbitTime:
    def __init__(self,Day):
        self.day = Day
        self.planet = []
        self.moon = []
        
    def addmoon(self,name,centroid,black,red,green,blue):
        self.moon.append(moon(name,centroid,black,red,green,blue))
        
    def addplanet(self,name,centroid,width):
        self.planet.append(planet(name,centroid,width))

In [9]:
dir='C:/Users/tvfer/Documents/AstroLab/TestOrbits/Jupiter/'

In [10]:
Blue22dir,Red22dir,Green22dir = dir+'22/jupiter_2019-10-22_18-56-17_Blue_0055.fits',dir+'22/jupiter_2019-10-22_18-53-24_Red_0035.fits', dir+'22/jupiter_2019-10-22_18-54-57_Green_0042.fits'

In [11]:
Red23dir = dir+'23/jupiter_2019-10-23_19-14-42_Red_0114.fits'

In [12]:
Black24dir,Blue24dir,Red24dir,Green24dir = dir+'24/jupiter_2019-10-24_18-23-22_black_0075.fits',dir+'24/jupiter_2019-10-24_18-27-28_Blue_0083.fits',dir+'24/jupiter_2019-10-24_18-32-06_Red_0109.fits',dir+'24/jupiter_2019-10-24_18-29-54_Green_0095.fits'

In [13]:
Black251dir,Blue251dir,Red251dir,Green251dir= dir+'25/jupiter_2019-10-25_18-24-58_black_0082.fits',dir+'25/jupiter_2019-10-25_18-25-41_Blue_0088.fits',dir+'25/jupiter_2019-10-25_18-29-40_Red_0103.fits',dir+'25/jupiter_2019-10-25_18-28-40_Green_0096.fits'
Black252dir,Blue252dir,Green252dir = dir+'25/jupiter_2019-10-25_19-26-54_black_0225.fits',dir+'25/jupiter_2019-10-25_19-27-22_Blue_0226.fits',dir+'25/jupiter_2019-10-25_19-34-01_Green_0242.fits'

In [14]:
Blue22,Red22,Green22 = fits.open(Blue22dir),fits.open(Red22dir),fits.open(Green22dir)
Red23 = fits.open(Red23dir)
Black24,Blue24,Red24,Green24 = fits.open(Black24dir),fits.open(Blue24dir), fits.open(Red24dir),fits.open(Green24dir)
Black251,Blue251,Red251,Green251 = fits.open(Black251dir),fits.open(Blue251dir),fits.open(Red251dir), fits.open(Green251dir)
Black252,Blue252,Green252 = fits.open(Black252dir),fits.open(Blue252dir), fits.open(Green252dir)

In [15]:

dictionaryDATA = [[-1,Red22,Blue22,Green22],[-1,Red23,-1,-1],[Black24,Red24,Green24,Blue24],[Black251,Red251,Green251,Blue251],[Black252,-1,Green252,Blue252]]
Blue22[0].header['JD'],Blue252[0].header['JD']

(2458779.2890561, 2458782.31064054)

In [16]:
TestRed22Centroids = [['Jupiter',716,631],['Io',670,631],['Calisto',915,609],-1,-1]
TestGreen22Centroids = [['Jupiter',718,632],['Io',671,637],['Calisto',915,617],-1,-1]
TestBlue22Centroids = [['Jupiter',714,637],['Io',670,640],['Calisto',910,623],-1,-1]
TestRed23Centroids = [['Jupiter',725,725],['Ganimedes',281,690],['Europa',412,715],['Calisto',580,682],-1]
TestBlack24Centroids = [['Jupiter',898,554],['Ganimedes',406,524],['Calisto',444,492],['Io',996,567],['Europa',1017,577]]
TestRed24Centroids = [['Jupiter',907,563],['Ganimedes',415,532],['Calisto',453,502],['Io',1010,576],['Europa',1031,584]]
TestGreen24Centroids = [['Jupiter',898,588],['Ganimedes',405,560],['Calisto',444,527],['Io',1000,603],['Europa',1021,611]]
TestBlue24Centroids = [['Jupiter',891,562],['Ganimedes',400,534],['Calisto',441,502],['Io',994,576],['Europa',1013,585]]
TestBlack251Centroids = [['Jupiter',761,483],['Ganimedes',568,480],['Io',592,458],['Europa',1030,510],-1]
TestRed251Centroids = [['Jupiter',767,498],['Ganimedes',578,496],['Io',604,475],['Europa',1037,522],-1]
TestGreen251Centroids = [['Jupiter',764,497],['Ganimedes',575,495],['Io',603,472],['Europa',1035,522],['Calisto',69,388]]
TestBlue251Centroids = [['Jupiter',762,489],['Ganimedes',571,487],['Io',602,466],['Europa',1037,519],-1]
TestBlack252Centroids = [['Jupiter',686,586],['Ganimedes',512,580],['Io',505,556],['Europa',936,610],-1]
TestBlue252Centroids = [['Jupiter',684,585],['Ganimedes',515,581],['Io',507,554],['Europa',939,605],-1]
TestGreen252Centroids = [['Jupiter',770,418],['Ganimedes',590,391],['Io',600,418],['Europa',1024,439],['Calisto',72,307]]
dictestC = [[-1,TestRed22Centroids,TestGreen22Centroids,TestBlue22Centroids],[-1,TestRed23Centroids,-1,-1],[TestBlack24Centroids,TestRed24Centroids,TestGreen24Centroids,TestBlue24Centroids],[TestBlack251Centroids,TestRed251Centroids,TestGreen251Centroids,TestBlue251Centroids],[TestBlack252Centroids,-1,TestGreen252Centroids,TestBlue252Centroids]]

In [17]:
Red22[0].data[716,631],(Red22[0].data[631-30:631+30,716-30:716+30])
jh = 0
jh+=1
jh

1

In [18]:
T = [1,1]
not isinstance(T,list)
dictestC[1][1][1][2]

690

In [131]:
ListofOrbitTimes = []

for j in range(0,len(dictionaryDATA)):
    dayinit = 0
    Blackl= []
    Redl= []
    Greenl = []
    Bluel = []
    centroidOrbit = []
    names = []
    filterno = ChooseMoreMoons(dictestC[j])
    for s in range(0,len(dictionaryDATA[j])):
        centroids = []
        namestemp = []
        if dictionaryDATA[j][s] == -1:
            if s == 0: Blackl = [-1,-1,-1,-1]
            if s == 1: Redl = [-1,-1,-1,-1]
            if s == 2: Greenl = [-1,-1,-1,-1]
            if s == 3: Bluel = [-1,-1,-1,-1]
        if dictionaryDATA[j][s]!=-1:
            
            if dayinit == 0:
                ListofOrbitTimes.append(OrbitTime(dictionaryDATA[j][filterno][0].header['JD']-2458779))
                centroidinit = 0
                dayinit = 1
            for s1 in range(0,5):
                if dictestC[j][s][s1]==-1:
                    centroids.append(-1)
                    namestemp.append(-1)
                if dictestC[j][s][s1]!=-1:
                    subdata = dictionaryDATA[j][s][0].data[dictestC[j][s][s1][2]-10:dictestC[j][s][s1][2]+10,dictestC[j][s][s1][1]-10:dictestC[j][s][s1][1]+10]
                    centroids.append(centroid_2dg(subdata) + [dictestC[j][s][s1][1],dictestC[j][s][s1][2]] - [10,10])
                    namestemp.append(dictestC[j][s][s1][0])
            if s == filterno:
                centroidOrbit = centroids
                names = namestemp
            for s2 in range(0,5):
                if s2 == 0 and s == filterno:
                    ListofOrbitTimes[j].addplanet(names[s2],centroidOrbit[s2] if dictionaryDATA[j][s][0].data[dictestC[j][s][s2][2],dictestC[j][s][s2][1]] < 65535 else [dictestC[j][s][s2][1],dictestC[j][s][s2][2]],66)
                    centroidinit = 1
                if s2 != 0 and not isinstance(centroids[s2],int):
                    if s == 0: Blackl.append((dictionaryDATA[j][s][0].data[int(centroids[s2][1]),int(centroids[s2][0])]-dictionaryDATA[j][s][0].data[10,10])/dictionaryDATA[j][s][0].header['EXPTIME'])
                    if s == 1: Redl.append((dictionaryDATA[j][s][0].data[int(centroids[s2][1]),int(centroids[s2][0])]-dictionaryDATA[j][s][0].data[10,10])/dictionaryDATA[j][s][0].header['EXPTIME'])
                    if s == 2: Greenl.append((dictionaryDATA[j][s][0].data[int(centroids[s2][1]),int(centroids[s2][0])]-dictionaryDATA[j][s][0].data[10,10])/dictionaryDATA[j][s][0].header['EXPTIME'])
                    if s == 3: Bluel.append((dictionaryDATA[j][s][0].data[int(centroids[s2][1]),int(centroids[s2][0])]-dictionaryDATA[j][s][0].data[10,10])/dictionaryDATA[j][s][0].header['EXPTIME'])
                if s2 != 0 and (isinstance(centroids[s2],int)):
                    if s == 0: Blackl.append(-1)
                    if s == 1: Redl.append(-1)
                    if s == 2: Greenl.append(-1)
                    if s == 3: Bluel.append(-1)
    for g in range(1,len(centroidOrbit)):
        if not isinstance(names[g],int):
            ListofOrbitTimes[j].addmoon(names[g],centroidOrbit[g],Blackl[g-1],Redl[g-1], Greenl[g-1], Bluel[g-1]) 

C:\Users\tvfer\Anaconda3\lib\site-packages\ipykernel_launcher.py:44: RuntimeWarning:

overflow encountered in ushort_scalars



In [24]:
ListofOrbitTimes[2].moon[0].rgb, ListofOrbitTimes[2].moon[1].rgb, ListofOrbitTimes[2].moon[2].rgb, ListofOrbitTimes[2].moon[3].rgb

([0.9550744842797942, 0.2879472699169431, 0.07013629035716243],
 [0.9515856940049027, 0.3009165326702296, 0.06272086838472567],
 [0.9719975087518797, 0.19358724756478943, 0.13320968643619077],
 [0.9923724901692692, 0.12314363984601212, 0.005699536886404418])

In [25]:
ListofOrbitTimes[3].moon[0].rgb, ListofOrbitTimes[3].moon[1].rgb, ListofOrbitTimes[3].moon[2].rgb, ListofOrbitTimes[3].moon[3].rgb

([0.921404706468336, 0.3717623096046203, 0.1131642702244742],
 [0.02173267777795916, 0.011011223407499307, 0.9997031777861215],
 [0.947834723596181, 0.2989236388117388, 0.11069776377551781],
 [-0.0008090609590777915, 0.9999993454201502, -0.0008090609590777915])

In [27]:
ListofOrbitTimes[1].moon[0].rgb, ListofOrbitTimes[1].moon[1].rgb, ListofOrbitTimes[1].moon[2].rgb

([0.9999737832752457, -0.0051201934627508735, -0.0051201934627508735],
 [0.9999299805695223, -0.008367614900163366, -0.008367614900163366],
 [0.9995108923964211, -0.022113072840628783, -0.022113072840628783])

In [28]:
for s in range(0,len(ListofOrbitTimes)):
    print(ListofOrbitTimes[s].planet[0].centroid)

[716, 631]
[724.72077741 724.12794826]
[898, 554]
[764, 497]
[770, 418]


In [132]:
ganidat = []
calistdat = []
iodat = []
eurodat = []
for s in range(0,len(ListofOrbitTimes)):
    for s1 in range(0,len(ListofOrbitTimes[s].moon)):
        if ListofOrbitTimes[s].moon[s1].name == 'Ganimedes': ganidat.append([ListofOrbitTimes[s].day,distance(ListofOrbitTimes[s].moon[s1].centroid,ListofOrbitTimes[s].planet[0].centroid,ListofOrbitTimes[s].planet[0].width)[0],distance(ListofOrbitTimes[s].moon[s1].centroid,ListofOrbitTimes[s].planet[0].centroid,ListofOrbitTimes[s].planet[0].width)[1]])
        if ListofOrbitTimes[s].moon[s1].name == 'Calisto': calistdat.append([ListofOrbitTimes[s].day,distance(ListofOrbitTimes[s].moon[s1].centroid,ListofOrbitTimes[s].planet[0].centroid,ListofOrbitTimes[s].planet[0].width)[0],distance(ListofOrbitTimes[s].moon[s1].centroid,ListofOrbitTimes[s].planet[0].centroid,ListofOrbitTimes[s].planet[0].width)[1]])
        if ListofOrbitTimes[s].moon[s1].name == 'Io': iodat.append([ListofOrbitTimes[s].day,distance(ListofOrbitTimes[s].moon[s1].centroid,ListofOrbitTimes[s].planet[0].centroid,ListofOrbitTimes[s].planet[0].width)[0],distance(ListofOrbitTimes[s].moon[s1].centroid,ListofOrbitTimes[s].planet[0].centroid,ListofOrbitTimes[s].planet[0].width)[1]])
        if ListofOrbitTimes[s].moon[s1].name == 'Europa': eurodat.append([ListofOrbitTimes[s].day,distance(ListofOrbitTimes[s].moon[s1].centroid,ListofOrbitTimes[s].planet[0].centroid,ListofOrbitTimes[s].planet[0].width)[0],distance(ListofOrbitTimes[s].moon[s1].centroid,ListofOrbitTimes[s].planet[0].centroid,ListofOrbitTimes[s].planet[0].width)[1]])


In [255]:
ganidat

[[1.30173770012334, 6.763124520022277, 0.453089406018638],
 [2.2661990500055254, 7.451086328023904, 0.4601305122319197],
 [3.269851880148053, 2.8555042865520823, 0.031071171540808316],
 [3.315214639995247, 2.6791594188914365, 0.45394733468599857]]

In [256]:
calistdat

[[0.28705404978245497, -2.992241370183759, 0.2921679177602493],
 [1.30173770012334, 2.2446202243990725, 0.5757951449764305],
 [2.2661990500055254, 6.867652706918825, 0.9624961276386719],
 [3.269851880148053, 10.586245687233989, 1.6386617099680079],
 [3.315214639995247, 10.579822424333448, 1.7725021867124664]]

In [257]:
iodat

[[0.28705404978245497, -0.19269239112486847, 0.12687492372046535],
 [2.2661990500055254, -1.4751151714330673, -0.1763254632450002],
 [3.269851880148053, 2.4752683038999246, 0.3652063300990123],
 [3.315214639995247, 2.5203794733504705, 0.06405986614675618]]

In [258]:
eurodat

[[1.30173770012334, 4.7531103734446365, 0.09426215811150356],
 [2.2661990500055254, -1.784004474800206, -0.29523202621384936],
 [3.269851880148053, -4.083418285821129, -0.3920135921782799],
 [3.315214639995247, -3.8756075624468993, -0.28896269908188266]]

In [259]:
fitfunc = lambda p, t: p[0]*np.cos(2*np.pi*t/p[1] + p[2])# Target function
errfunc = lambda p, t, y: (fitfunc(p, t) - y) # Distance to the target function
p0ganix = [8, 7, 1] # Initial guess for the parameters
p0ganiy = [0.5, 7, 0]
p0calistx = [10, 16, 0]
p0calisty = [2, 5, 0]
p0iox = [4, 1.7, 0]
p0ioy = [2,1.7,0.]
p0eurox = [5, 3.55, 3]
p0euroy = [0.4, 3.55, 0]

p1ganix, successganix = optimize.leastsq(errfunc, p0ganix[:], args=(np.asarray(selectdata(ganidat,0), dtype=np.float64), np.asarray(selectdata(ganidat,1), dtype=np.float64)))
p1ganiy, successganiy = optimize.leastsq(errfunc, p0ganiy[:], args=(np.asarray(selectdata(ganidat,0), dtype=np.float64), np.asarray(selectdata(ganidat,2), dtype=np.float64)))

p1calistx, successcalistx = optimize.leastsq(errfunc, p0calistx[:], args=(np.asarray(selectdata(calistdat,0), dtype=np.float64), np.asarray(selectdata(calistdat,1), dtype=np.float64)))
p1calisty, successcalisty = optimize.leastsq(errfunc, p0calisty[:], args=(np.asarray(selectdata(calistdat,0), dtype=np.float64), np.asarray(selectdata(calistdat,2), dtype=np.float64)))

p1iox, successiox = optimize.leastsq(errfunc, p0iox[:], args=(np.asarray(selectdata(iodat,0), dtype=np.float64), np.asarray(selectdata(iodat,1), dtype=np.float64)))
p1ioy, successioy = optimize.leastsq(errfunc, p0ioy[:], args=(np.asarray(selectdata(iodat,0), dtype=np.float64), np.asarray(selectdata(iodat,2), dtype=np.float64)))

p1geurox, successeurox = optimize.leastsq(errfunc, p0eurox[:], args=(np.asarray(selectdata(eurodat,0), dtype=np.float64), np.asarray(selectdata(eurodat,1), dtype=np.float64)))
p1geuroy, successeuroy = optimize.leastsq(errfunc, p0euroy[:], args=(np.asarray(selectdata(eurodat,0), dtype=np.float64), np.asarray(selectdata(eurodat,2), dtype=np.float64)))

In [273]:
p1ganix,p1ganiy

(array([-7.82916416,  7.20145464,  1.47815354]),
 array([-0.47323783,  9.79673839,  2.0474309 ]))

In [261]:
p1calistx,p1calisty

(array([12.49902252, 15.09077649, -1.93216968]),
 array([ 349.83934167, 4520.78540516,    4.71248357]))

In [262]:
p1iox,p1ioy

(array([3.09135293, 1.83466448, 0.6383013 ]),
 array([ 0.2357581 ,  1.55574774, -0.195911  ]))

In [263]:
p1geurox,p1geuroy

(array([4.8893537 , 3.55103326, 4.21760168]),
 array([ 0.38869264,  5.36587851, -0.20358643]))

In [268]:
Djupiter = 142984e+03
G = 6.674e-11
alpha = np.power(Djupiter,3)*4*np.pi*np.pi/(G*(60*60*24)*(60*60*24))
alpha

2.3163723728837372e+26

In [269]:
M = [alpha*np.power(p1ganix[0]*p1ganix[0] + p1ganiy[0]*p1ganiy[0],3/2)/(p1ganix[1]*p1ganix[1]),alpha*np.power(p1calistx[0]*p1calistx[0],3/2)/(p1calistx[1]*p1calistx[1]),alpha*np.power(p1iox[0]*p1iox[0] + p1ioy[0]*p1ioy[0],3/2)/(p1iox[1]*p1iox[1]),alpha*np.power(p1geurox[0]*p1geurox[0] + p1geuroy[0]*p1geuroy[0],3/2)/(p1geurox[1]*p1geurox[1])]

In [270]:
M

[2.155211637849715e+27,
 1.986155990083772e+27,
 2.050778483324687e+27,
 2.16749122661886e+27]

In [267]:
MJup = 1.8982e+27

In [274]:
fig1 = go.Figure()


t1 = np.linspace(1,3.4,100)
t0 = np.linspace(0,3.4,100)

fig1.add_trace(go.Scatter(x = t1, y = -p1ganix[0]*np.sin(2*t1*np.pi/p1ganix[1] + p1ganix[2]-1.57),mode='lines', name='Ganimedes(fit)'))
fig1.add_trace(go.Scatter(x = selectdata(ganidat,0), y = selectdata(ganidat,1), mode='markers', name='Ganimedes(data)'))

In [272]:
fig2 = go.Figure()


fig2.add_trace(go.Scatter(x = t0, y = (p1calistx[0])*np.sin(2*t1*np.pi/p1calistx[1] + p1calistx[2]+1.3),mode='lines', name='Callisto(fit)'))
fig2.add_trace(go.Scatter(x = selectdata(calistdat,0), y = selectdata(calistdat,1), mode='markers', name='Callisto(data)'))

In [183]:
fig3 = go.Figure()


fig3.add_trace(go.Scatter(x = t0, y = p1iox[0]*np.sin(2*t1*np.pi/p1iox[1] + p1iox[2]+1.5),mode='lines', name='Io(fit)'))
fig3.add_trace(go.Scatter(x = selectdata(iodat,0), y = selectdata(iodat,1), mode='markers',name='Io(data)'))

In [216]:
fig4 = go.Figure()
fig4.add_trace(go.Scatter(x = t0, y = p1geurox[0]*np.sin(2*t1*np.pi/(p1geurox[1]) + p1geurox[2]+0.8),mode='lines', name='Europa(fit)'))
fig4.add_trace(go.Scatter(x = selectdata(eurodat,0), y = selectdata(eurodat,1), mode='markers',name='Europa(data)'))